_BASE_: "../Base_scratch_classifier_R50_gn_avgpool.yaml"
INPUT:
  FORMAT: "L"
  RANDOM_FLIP: "none"
  MIN_SIZE_TRAIN: [28]
  MAX_SIZE_TRAIN: 28
  MIN_SIZE_TEST: 28
  MAX_SIZE_TEST: 28
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  FILTER_EMPTY_ANNOTATIONS: False
MODEL:
  PIXEL_MEAN: [33.3184]
  PIXEL_STD: [78.5675]
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  CLASSIFIER_HEAD:
    NUM_CLASSES: 10
DATASETS:
  TRAIN: ("mnist_train",)
  TEST: ("mnist_test",)
SOLVER:
  CHECKPOINT_PERIOD: 200
  MAX_ITER: 5000
  IMS_PER_BATCH: 64
  STEPS: (4750, 4900)
  BASE_LR: 0.01
  WARMUP_ITERS: 50
TEST:
  EVAL_PERIOD: 100
