INPUT:
  FORMAT: "L"
  RANDOM_FLIP: "none"
  MIN_SIZE_TRAIN: [28]
  MAX_SIZE_TRAIN: 28
  MIN_SIZE_TEST: 28
  MAX_SIZE_TEST: 28
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  FILTER_EMPTY_ANNOTATIONS: False
MODEL:
  WEIGHTS: ""
  PIXEL_MEAN: [33.3184]
  PIXEL_STD: [78.5675]
  META_ARCHITECTURE: "UxClassifier"
  UNSUPERVISED_OBJECTIVE:
    NAME: "FullyConnectedImageDecoder"
  BACKBONE:
    NAME: "FullyConnectedBackbone"
  CLASSIFIER_HEAD:
    NAME: "LinearClassifierHead"
    NUM_CLASSES: 10
    IN_FEATURES: ["out"]
  FULLY_CONNECTED_BACKBONE:
    INPUT_SIZE: 784
    OUT_FEATURES: ["out"]
    LAYER_SIZES: [100, 50]
    LAYER_NORMS: ["", ""]
    LAYER_ACTIVATIONS: ["relu", "relu"]
  IMAGE_DECODER:
    IN_FEATURES: ["out"]
    LAYER_SIZES: [100, 784]
    LAYER_NORMS: ["", ""]
    LAYER_ACTIVATIONS: ["relu", "identity"]
    OUTPUT_HEIGHT: 28
    OUTPUT_WIDTH: 28

DATASETS:
  TRAIN: ("mnist_train",)
  TEST: ("mnist_test",)
SOLVER:
  AMP:
    ENABLED: False
  CHECKPOINT_PERIOD: 200
  MAX_ITER: 5000
  IMS_PER_BATCH: 64
  STEPS: (4750, 4900)
  BASE_LR: 0.01
  WARMUP_ITERS: 50
  WARMUP_METHOD: "linear"
  GAMMA: 0.1 # drop LR by 10x after each of "STEPS" iters
TEST:
  EVAL_PERIOD: 100
VERSION: 2
