_BASE_: "../Base_scratch_uxrcnn_R50FPN_6x.yaml"
MODEL:
  META_ARCHITECTURE: "UxRCNN"
  UNSUPERVISED_OBJECTIVE:
    NAME: "ImageDecoder"
  IMAGE_DECODER:
    LOSS_WEIGHT: 0.5
    LOSS_KEY: "loss_image_decoder"
    COMMON_STRIDE: 4
    IN_FEATURES: ["p5"]
    SCALE_HEADS_DIM: 64
    SCALE_HEADS_NORM: ""
    PREDICTOR_DEPTH: 1
    PREDICTOR_DIM: -1
    PREDICTOR_NORM: ""
#SOLVER:
#  WARMUP_ITERS: 2500
#  WARMUP_FACTOR: 0.0001
