_BASE_: "./Base_scratch_rcnn_R50FPN_5x_gn.yaml"
MODEL:
  META_ARCHITECTURE: "UxRCNN"
  UNSUPERVISED_OBJECTIVE:
    NAME: "ImageDecoder"
  IMAGE_DECODER:
    LOSS_WEIGHT: 0.5
    LOSS_KEY: "loss_image_decoder"
    COMMON_STRIDE: 4
    IN_FEATURES: ["p5"]
    SCALE_HEADS_DIM: 64
    SCALE_HEADS_NORM: ""
    PREDICTOR_DEPTH: 1
    PREDICTOR_DIM: -1 # easy choice is =SCALE_HEADS_DIM when PREDICTOR_DEPTH > 1
    PREDICTOR_NORM: ""
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
SOLVER:
  WARMUP_ITERS: 2500
  WARMUP_FACTOR: 0.0001
